2024-09-10 17:08:42,066 INFO    StreamThr :532521 [internal.py:wandb_internal():85] W&B internal server running at pid: 532521, started at: 2024-09-10 17:08:42.065953
2024-09-10 17:08:42,067 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:08:42,068 INFO    WriterThread:532521 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/run-fim7dktv.wandb
2024-09-10 17:08:42,070 DEBUG   SenderThread:532521 [sender.py:send():391] send: header
2024-09-10 17:08:42,071 DEBUG   SenderThread:532521 [sender.py:send():391] send: run
2024-09-10 17:08:42,286 INFO    SenderThread:532521 [dir_watcher.py:__init__():211] watching files in: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/files
2024-09-10 17:08:42,286 INFO    SenderThread:532521 [sender.py:_start_run_threads():1200] run started: fim7dktv with start time 1725988122.065465
2024-09-10 17:08:42,291 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: check_version
2024-09-10 17:08:42,291 DEBUG   SenderThread:532521 [sender.py:send_request():418] send_request: check_version
2024-09-10 17:08:42,352 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: run_start
2024-09-10 17:08:44,404 DEBUG   HandlerThread:532521 [system_info.py:__init__():26] System info init
2024-09-10 17:08:44,404 DEBUG   HandlerThread:532521 [system_info.py:__init__():41] System info init done
2024-09-10 17:08:44,404 INFO    HandlerThread:532521 [system_monitor.py:start():194] Starting system monitor
2024-09-10 17:08:44,404 INFO    SystemMonitor:532521 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-10 17:08:44,404 INFO    HandlerThread:532521 [system_monitor.py:probe():214] Collecting system info
2024-09-10 17:08:44,405 INFO    SystemMonitor:532521 [interfaces.py:start():188] Started cpu monitoring
2024-09-10 17:08:44,405 INFO    SystemMonitor:532521 [interfaces.py:start():188] Started disk monitoring
2024-09-10 17:08:44,406 INFO    SystemMonitor:532521 [interfaces.py:start():188] Started gpu monitoring
2024-09-10 17:08:44,407 INFO    SystemMonitor:532521 [interfaces.py:start():188] Started memory monitoring
2024-09-10 17:08:44,409 INFO    SystemMonitor:532521 [interfaces.py:start():188] Started network monitoring
2024-09-10 17:08:44,736 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,743 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,745 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,745 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,745 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,745 DEBUG   HandlerThread:532521 [system_info.py:probe():152] Probing system
2024-09-10 17:08:44,745 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,746 DEBUG   HandlerThread:532521 [system_info.py:_probe_git():137] Probing git
2024-09-10 17:08:44,747 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,752 DEBUG   HandlerThread:532521 [system_info.py:_probe_git():145] Probing git done
2024-09-10 17:08:44,752 DEBUG   HandlerThread:532521 [system_info.py:probe():200] Probing system done
2024-09-10 17:08:44,752 DEBUG   HandlerThread:532521 [system_monitor.py:probe():223] {'os': 'Linux-5.19.0-1010-nvidia-lowlatency-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-09-10T17:08:44.745436', 'startedAt': '2024-09-10T17:08:42.061758', 'docker': None, 'cuda': None, 'args': ('--wallet.name', 'Alice', '--wallet.hotkey', 'Eve', '--subtensor.network', 'test', '--device', 'cuda:5', '--use_wandb'), 'state': 'running', 'program': '/home/ubuntu/frontend/bistro/miner.py', 'codePathLocal': 'miner.py', 'codePath': 'bistro/miner.py', 'git': {'remote': 'https://github.com/unconst/frontend.git', 'commit': 'a0660981f23476af1751d70673e4586879b6970c'}, 'email': 'jake@bittensor.com', 'root': '/home/ubuntu/frontend', 'host': 'training', 'username': 'ubuntu', 'executable': '/home/ubuntu/frontend/venv/bin/python3', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2182.2359453125, 'min': 1500.0, 'max': 3250.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3801.118, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3799.205, 'min': 1500.0, 'max': 3250.0}, {'current': 3807.605, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3807.945, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3810.855, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2291.021, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.153, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.113, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.11, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.121, 'min': 1500.0, 'max': 3250.0}, {'current': 3799.57, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.124, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.148, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.12, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}], 'disk': {'/': {'total': 3519.6199798583984, 'used': 90.96331787109375}}, 'gpu': 'NVIDIA H100 PCIe', 'gpu_count': 8, 'memory': {'total': 1511.5785369873047}}
2024-09-10 17:08:44,753 INFO    HandlerThread:532521 [system_monitor.py:probe():224] Finished collecting system info
2024-09-10 17:08:44,753 INFO    HandlerThread:532521 [system_monitor.py:probe():227] Publishing system info
2024-09-10 17:08:44,753 INFO    HandlerThread:532521 [system_monitor.py:probe():229] Finished publishing system info
2024-09-10 17:08:44,755 DEBUG   SenderThread:532521 [sender.py:send():391] send: files
2024-09-10 17:08:44,755 INFO    SenderThread:532521 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-09-10 17:08:44,860 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: python_packages
2024-09-10 17:08:44,860 DEBUG   SenderThread:532521 [sender.py:send_request():418] send_request: python_packages
2024-09-10 17:08:44,862 DEBUG   SenderThread:532521 [sender.py:send():391] send: telemetry
2024-09-10 17:08:44,903 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:44,903 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:08:44,903 DEBUG   SenderThread:532521 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:08:45,288 INFO    Thread-12 :532521 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/files/requirements.txt
2024-09-10 17:08:45,289 INFO    Thread-12 :532521 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/files/wandb-metadata.json
2024-09-10 17:08:45,670 INFO    wandb-upload_0:532521 [upload_job.py:push():130] Uploaded file /tmp/tmpc4ep8ln_wandb/7vqindez-wandb-metadata.json
2024-09-10 17:08:45,902 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:46,747 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,747 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,747 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,747 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,747 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,748 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,748 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:47,199 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:08:47,201 DEBUG   SenderThread:532521 [sender.py:send():391] send: history
2024-09-10 17:08:47,201 DEBUG   SenderThread:532521 [sender.py:send_request():418] send_request: summary_record
2024-09-10 17:08:47,202 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:08:47,204 INFO    SenderThread:532521 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-10 17:08:47,288 INFO    Thread-12 :532521 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/files/wandb-summary.json
2024-09-10 17:08:47,289 INFO    Thread-12 :532521 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/files/output.log
2024-09-10 17:08:47,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:48,750 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,751 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,751 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,751 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,751 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,751 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,751 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:49,277 ERROR   FileStreamThread:532521 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/const69/bistro/fim7dktv/file_stream
NoneType: None
2024-09-10 17:08:49,289 INFO    Thread-12 :532521 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/files/output.log
2024-09-10 17:08:49,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:50,824 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:50,871 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:51,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:52,862 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:08:52,867 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:52,908 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,320 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,320 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,400 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,441 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,442 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,442 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,442 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,442 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,442 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:57,863 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:08:59,301 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,303 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,304 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,304 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,304 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,304 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,304 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,307 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,325 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:02,864 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:09:04,393 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,453 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,453 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,453 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,453 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,453 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,453 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,515 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,555 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,555 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,555 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,555 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,555 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,556 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:07,865 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:09:08,572 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,646 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,675 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,675 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,675 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,675 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,675 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,675 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:11,970 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:11,971 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:09:11,971 DEBUG   SenderThread:532521 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:09:12,716 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,718 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,718 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,718 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,718 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,718 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,718 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:12,969 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:13,034 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:09:13,068 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:13,068 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:13,970 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:14,290 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:14,290 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:14,819 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,945 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,945 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,945 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,945 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,945 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,945 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:14,969 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:15,969 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:16,604 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:16,604 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:16,604 INFO    SenderThread:532521 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:09:16,971 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:16,989 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,045 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,045 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,045 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,045 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,045 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,045 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,971 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:18,970 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:19,045 ERROR   gpu       :532521 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:09:19,222 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,357 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,357 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,357 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,357 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,357 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,357 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,970 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:20,971 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:21,397 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,444 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,445 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,445 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,445 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,445 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,445 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,597 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:21,597 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:21,972 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:23,149 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:23,515 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,640 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,640 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,640 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,640 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,640 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,640 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:24,148 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:25,149 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:25,684 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:25,764 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:25,764 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:25,764 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:25,764 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:25,764 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:25,764 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,150 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:26,969 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:09:27,149 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:27,866 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:27,967 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:27,968 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:27,968 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:27,968 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:27,968 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:27,968 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,149 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:29,149 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:30,018 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,051 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,051 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,051 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,051 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,051 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,051 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,150 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:31,341 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:31,589 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:31,589 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:32,119 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,193 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,194 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,194 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,194 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,194 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,194 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,341 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:33,341 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:34,209 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,239 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,239 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,239 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,239 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,239 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,239 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,341 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:35,341 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:36,341 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:36,384 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,480 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,480 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,480 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,480 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,480 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,480 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:37,342 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:38,342 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:38,515 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:38,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:38,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:38,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:38,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:38,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:38,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,830 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:40,650 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,683 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,683 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,683 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,683 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,683 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,683 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:40,830 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:41,830 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:42,778 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:42,831 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:42,868 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:42,869 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:42,869 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:42,869 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:42,869 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:42,869 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,831 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:44,409 DEBUG   SystemMonitor:532521 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-10 17:09:44,831 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:44,908 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:44,910 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:44,910 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:44,910 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:44,910 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:44,910 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:44,910 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,831 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:46,831 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:46,964 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,032 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,032 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,032 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,032 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,033 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,033 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:48,215 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:49,121 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,186 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,186 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,186 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,186 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,186 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,186 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,215 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:49,502 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:49,502 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:50,215 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:51,186 ERROR   gpu       :532521 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:09:51,216 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:51,302 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,390 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,390 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,390 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,390 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,390 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,390 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:52,215 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:53,215 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:53,463 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,557 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:54,216 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:55,216 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:55,641 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:55,741 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:55,742 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:55,742 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:55,742 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:55,742 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:55,742 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,216 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:57,217 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:57,795 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:57,893 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:57,893 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:57,893 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:57,893 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:57,893 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:57,894 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,217 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:59,217 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:00,010 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,094 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,094 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,094 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,094 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,094 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,094 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,217 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:01,217 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,129 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,218 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:03,218 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:04,162 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,218 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:04,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:05,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:06,382 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,438 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,438 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,438 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,438 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,438 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,438 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,515 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:07,515 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:08,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:08,626 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,743 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,744 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,744 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,744 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,744 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,744 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:09,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:10,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:10,835 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:10,897 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:10,897 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:10,897 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:10,897 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:10,897 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:10,897 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:12,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:12,927 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:12,959 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:12,959 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:12,959 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:12,959 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:12,959 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:12,959 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,516 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:14,517 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:14,974 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,042 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,042 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,042 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,042 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,042 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,042 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,518 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:16,517 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:17,101 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,102 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,102 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,102 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,102 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,102 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,102 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,517 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:18,517 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:19,188 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,242 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,242 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,242 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,242 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,242 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,242 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,517 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:20,517 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:21,274 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,337 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,337 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,337 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,337 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,337 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,337 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,518 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:22,518 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:23,337 ERROR   gpu       :532521 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:10:23,339 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,363 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,363 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,363 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,363 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,364 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,364 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,518 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:24,353 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:10:24,353 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:10:24,518 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:25,409 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,455 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,455 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,455 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,455 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,455 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,455 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,518 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:26,519 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:27,489 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,519 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:27,547 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,547 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,547 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,547 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,548 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,548 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:28,519 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:29,519 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,550 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:30,519 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:31,519 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:31,561 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,563 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,563 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,563 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,564 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,564 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,564 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:32,521 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:33,567 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,572 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,572 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:34,030 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:34,996 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:35,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,573 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,997 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:36,997 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:37,415 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,574 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,997 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:38,997 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,575 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,941 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:39,997 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:40,249 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:40,539 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:40,829 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:40,997 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:41,118 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,408 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,576 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,698 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,987 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:42,277 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:42,567 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:42,856 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:42,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:43,145 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,435 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,725 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:44,014 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,304 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,594 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,884 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:45,176 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,466 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,577 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,761 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:46,056 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:46,352 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:46,648 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:46,945 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:46,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,578 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:48,998 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,579 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,999 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:50,999 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,580 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,999 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:52,999 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:53,580 ERROR   gpu       :532521 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,581 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,999 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:55,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:56,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:57,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:57,090 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,380 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,582 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,583 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,583 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,583 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,583 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,583 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,583 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,673 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,968 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:58,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:58,258 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:58,548 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:58,843 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:59,133 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,430 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,724 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:00,014 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,310 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,606 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,897 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:01,191 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,481 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,584 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,776 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:02,000 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:02,072 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:02,362 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:02,658 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:02,948 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:03,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:03,243 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:03,533 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,830 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:04,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:04,120 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:05,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:05,585 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:06,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:07,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:07,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,586 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:08,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:09,001 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,587 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:10,002 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:11,002 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,588 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:12,002 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:12,476 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:12,767 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,002 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:13,057 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,348 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,643 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,932 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:14,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:14,222 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:14,511 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:14,801 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:15,090 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,380 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,589 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,670 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,959 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:16,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:16,249 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:16,538 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:16,827 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:17,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:17,116 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:17,406 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:17,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,590 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,696 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:17,985 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:18,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:18,275 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:18,565 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:18,854 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:19,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:19,143 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:19,432 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,591 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:20,003 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:21,004 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,592 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:22,004 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:23,004 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,593 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:24,005 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:25,005 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:26,005 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:27,005 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:27,594 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:28,005 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:29,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:29,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,595 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:30,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:31,007 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:31,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,596 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:32,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:33,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:33,597 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:34,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:35,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:35,598 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:36,008 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:37,006 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:37,599 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:38,007 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:39,008 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:39,600 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:40,007 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:41,007 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:41,601 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:42,007 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:43,007 DEBUG   HandlerThread:532521 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:43,444 ERROR   SenderThread:532521 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:11:43,444 ERROR   SenderThread:532521 [internal_api.py:execute():350] {"errors":[{"message":"run fim7dktv was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,602 ERROR   gpu       :532521 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:43,920 INFO    WriterThread:532521 [datastore.py:close():296] close: /home/ubuntu/frontend/bistro/wandb/run-20240910_170842-fim7dktv/run-fim7dktv.wandb
2024-09-10 17:11:44,008 INFO    HandlerThread:532521 [handler.py:finish():880] shutting down handler
2024-09-10 17:11:44,008 INFO    HandlerThread:532521 [system_monitor.py:finish():203] Stopping system monitor
2024-09-10 17:11:44,009 INFO    HandlerThread:532521 [interfaces.py:finish():200] Joined cpu monitor
2024-09-10 17:11:44,009 DEBUG   SystemMonitor:532521 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-10 17:11:44,009 ERROR   gpu       :532521 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:11:44,010 INFO    HandlerThread:532521 [interfaces.py:finish():200] Joined disk monitor
2024-09-10 17:11:44,010 DEBUG   SystemMonitor:532521 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-10 17:11:44,010 INFO    HandlerThread:532521 [interfaces.py:finish():200] Joined gpu monitor
2024-09-10 17:11:44,013 INFO    HandlerThread:532521 [interfaces.py:finish():200] Joined memory monitor
2024-09-10 17:11:44,013 INFO    HandlerThread:532521 [interfaces.py:finish():200] Joined network monitor
2024-09-10 17:11:44,265 ERROR   StreamThr :532521 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2224, in upsert_run
    response = self.gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 92, in _run
    self._debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 333, in _debounce
    self._sm.debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 549, in debounce
    self._maybe_update_config(always=final)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 526, in _maybe_update_config
    self._debounce_config()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 555, in _debounce_config
    self._api.upsert_run(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run fim7dktv was previously created and deleted; try a new run name (Error 409: Conflict)
