2024-09-10 17:02:47,099 INFO    StreamThr :514501 [internal.py:wandb_internal():85] W&B internal server running at pid: 514501, started at: 2024-09-10 17:02:47.098704
2024-09-10 17:02:47,101 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:02:47,102 INFO    WriterThread:514501 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/run-Miner-5EkVG.wandb
2024-09-10 17:02:47,103 DEBUG   SenderThread:514501 [sender.py:send():391] send: header
2024-09-10 17:02:47,106 DEBUG   SenderThread:514501 [sender.py:send():391] send: run
2024-09-10 17:02:47,110 INFO    SenderThread:514501 [sender.py:_setup_resume():761] checking resume status for None/bistro/Miner-5EkVG
2024-09-10 17:02:47,289 INFO    SenderThread:514501 [sender.py:_setup_resume():841] configured resuming with: ResumeState(resumed=True,step=1,history=1,events=0,output=6,runtime=5,wandb_runtime=None,summary={'_runtime': 5.3013787269592285, '_step': 0, '_timestamp': 1725987640.6544158, 'block': 2767843, 'master': 0, 'step': 1},config={'device': {'value': 'cuda:2'}, 'config': {'value': None}, 'use_wandb': {'value': True}, 'optimizer_weight_decay': {'value': 0.1}, 'history_size': {'value': 4}, 'bucket': {'value': 'decis'}, 'name': {'value': None}, 'strict': {'value': False}, 'no_prompt': {'value': False}, 'learning_rate': {'value': 0.0001}, 'subtensor': {'value': {'chain_endpoint': 'wss://entrypoint-finney.opentensor.ai:443', 'network': 'test', '_mock': False}}, 'netuid': {'value': 212}, 'optimizer_beta1': {'value': 0.9}, 'eval_window': {'value': 5}, '__is_set': {'value': {'subtensor.network': True, 'device': True, 'use_wandb': True, 'wallet.hotkey': True, 'wallet.name': True}}, 'batch_size': {'value': 4}, '_wandb': {'value': {'is_jupyter_run': False, 'python_version': '3.10.12', 'is_kaggle_kernel': False, 'huggingface_version': '4.44.2', 't': {'6': '4.44.2', '8': [5], '13': 'linux-x86_64', '1': [1, 11, 49, 55, 71], '2': [1, 11, 49, 55, 71], '3': [13, 14, 16, 23], '4': '3.10.12', '5': '0.17.7'}, 'framework': 'huggingface', 'start_time': 1725987635, 'cli_version': '0.17.7'}}, 'wallet': {'value': {'hotkey': 'Bob', 'path': '~/.bittensor/wallets/', 'name': 'Alice'}}, 'optimizer_beta2': {'value': 0.95}, 'no_version_checking': {'value': False}},tags=[])
2024-09-10 17:02:47,413 INFO    SenderThread:514501 [dir_watcher.py:__init__():211] watching files in: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files
2024-09-10 17:02:47,413 INFO    SenderThread:514501 [sender.py:_start_run_threads():1200] run started: Miner-5EkVG with start time 1725987762.09844
2024-09-10 17:02:47,414 DEBUG   SenderThread:514501 [sender.py:send_request():418] send_request: summary_record
2024-09-10 17:02:47,414 INFO    SenderThread:514501 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-10 17:02:47,418 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: check_version
2024-09-10 17:02:47,419 DEBUG   SenderThread:514501 [sender.py:send_request():418] send_request: check_version
2024-09-10 17:02:47,486 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: run_start
2024-09-10 17:02:48,414 INFO    Thread-12 :514501 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files/wandb-summary.json
2024-09-10 17:02:48,538 DEBUG   HandlerThread:514501 [system_info.py:__init__():26] System info init
2024-09-10 17:02:48,538 DEBUG   HandlerThread:514501 [system_info.py:__init__():41] System info init done
2024-09-10 17:02:48,538 INFO    HandlerThread:514501 [system_monitor.py:start():194] Starting system monitor
2024-09-10 17:02:48,539 INFO    SystemMonitor:514501 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-10 17:02:48,539 INFO    SystemMonitor:514501 [interfaces.py:start():188] Started cpu monitoring
2024-09-10 17:02:48,540 INFO    SystemMonitor:514501 [interfaces.py:start():188] Started disk monitoring
2024-09-10 17:02:48,541 INFO    SystemMonitor:514501 [interfaces.py:start():188] Started gpu monitoring
2024-09-10 17:02:48,542 INFO    SystemMonitor:514501 [interfaces.py:start():188] Started memory monitoring
2024-09-10 17:02:48,544 INFO    SystemMonitor:514501 [interfaces.py:start():188] Started network monitoring
2024-09-10 17:02:48,639 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: python_packages
2024-09-10 17:02:48,640 DEBUG   SenderThread:514501 [sender.py:send_request():418] send_request: python_packages
2024-09-10 17:02:48,640 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:02:48,641 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:48,641 DEBUG   SenderThread:514501 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:02:48,743 DEBUG   SenderThread:514501 [sender.py:send():391] send: telemetry
2024-09-10 17:02:49,414 INFO    Thread-12 :514501 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files/requirements.txt
2024-09-10 17:02:49,476 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,504 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,507 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,507 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,508 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,508 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,598 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:49,757 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:50,717 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:50,922 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:02:50,923 DEBUG   SenderThread:514501 [sender.py:send():391] send: history
2024-09-10 17:02:50,924 DEBUG   SenderThread:514501 [sender.py:send_request():418] send_request: summary_record
2024-09-10 17:02:50,924 INFO    SenderThread:514501 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-10 17:02:51,414 INFO    Thread-12 :514501 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files/wandb-summary.json
2024-09-10 17:02:51,415 INFO    Thread-12 :514501 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files/output.log
2024-09-10 17:02:51,598 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:51,717 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:52,717 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:52,965 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:02:53,415 INFO    Thread-12 :514501 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files/output.log
2024-09-10 17:02:53,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,599 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,600 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,600 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,600 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,600 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,600 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:53,717 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:54,717 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:55,718 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:56,293 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,294 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,718 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:57,718 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:58,314 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,377 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,377 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,642 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:00,403 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,416 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,421 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,421 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:03,643 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:04,471 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,473 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,473 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,571 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,596 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,597 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,597 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,597 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,597 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,597 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,632 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,644 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:08,670 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,670 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,670 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,670 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,670 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,670 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,713 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,772 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,772 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,772 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,772 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,772 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,773 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,234 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,645 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:14,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:03:14,544 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:14,544 DEBUG   SenderThread:514501 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:03:15,272 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,542 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:16,542 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:17,387 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,449 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,449 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,449 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,450 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,450 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,450 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,542 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:18,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:19,463 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:19,494 ERROR   FileStreamThread:514501 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/const69/bistro/Miner-5EkVG/file_stream
NoneType: None
2024-09-10 17:03:19,497 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:19,497 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:19,540 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,575 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,575 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,575 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,575 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,575 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,575 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,583 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:20,424 INFO    Thread-12 :514501 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/files/output.log
2024-09-10 17:03:20,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:20,581 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:20,582 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:21,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:21,575 ERROR   gpu       :514501 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:03:21,604 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:22,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:23,088 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:23,088 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:23,088 INFO    SenderThread:514501 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:03:23,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:23,657 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:24,543 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:25,544 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:25,719 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:26,544 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:27,544 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:27,715 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:27,715 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:27,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,545 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:29,541 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:03:29,581 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:30,100 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,131 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,131 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,545 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:31,545 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:32,169 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,545 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:33,545 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:34,277 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,368 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,368 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,368 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,368 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,368 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:35,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:36,444 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,545 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:36,932 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:36,932 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:37,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:38,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:38,634 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,666 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:39,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:40,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:40,689 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:41,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:42,563 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:42,724 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:43,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:44,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:44,883 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:45,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:46,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:46,996 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,121 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,122 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,122 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,122 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,122 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,122 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:48,544 DEBUG   SystemMonitor:514501 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-10 17:03:48,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:49,135 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,235 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,235 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,235 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,235 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,236 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:50,564 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:51,262 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,299 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,299 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,299 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,299 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,299 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,299 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:52,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:53,299 ERROR   gpu       :514501 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:03:53,337 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,363 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,363 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,363 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,363 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,363 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,364 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:54,184 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:54,184 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:54,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:55,406 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,463 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,463 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,463 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,463 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,463 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,463 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:56,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:57,546 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,565 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:57,583 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,583 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,583 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,583 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,583 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,583 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:58,566 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:59,566 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:59,622 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,625 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,625 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,625 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,625 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,625 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,625 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:00,566 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:01,567 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:01,692 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,830 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,830 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,830 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,830 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,830 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,831 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:02,567 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:03,567 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:03,904 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,026 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,026 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,026 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,026 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,026 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,026 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,567 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:05,567 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:06,126 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,234 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,234 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,234 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,234 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,234 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,235 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,568 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:08,304 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,332 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,332 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,332 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,332 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,332 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,332 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,334 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:09,333 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:10,334 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:10,424 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,480 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,481 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,481 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,481 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,481 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,481 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:11,334 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:12,334 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:12,516 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,518 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,518 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,518 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,518 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,518 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,518 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:13,403 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:14,402 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:14,567 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:15,402 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:16,403 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:16,704 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,732 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,732 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,732 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,732 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,732 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,732 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:17,403 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:18,403 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:18,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:19,403 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:20,403 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:20,903 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,952 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,952 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:21,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:22,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:23,028 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:24,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:25,090 ERROR   gpu       :514501 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:04:25,169 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,174 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,174 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:26,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:26,575 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:04:26,575 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:04:27,212 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:28,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:29,321 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,322 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,322 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,322 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,322 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,404 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:30,405 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:31,405 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:31,411 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,512 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:32,405 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:33,405 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:33,580 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:34,405 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:35,406 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:35,751 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,783 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:36,406 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:37,406 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:37,792 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,801 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:40,893 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:41,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,802 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,851 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:42,851 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:43,230 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,803 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,851 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:44,851 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:45,694 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,851 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:46,015 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:46,320 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:46,627 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:46,852 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:46,940 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,242 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,552 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,804 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,852 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:47,864 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,171 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,482 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,793 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,852 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:49,101 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:49,407 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:49,715 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,805 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,852 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:50,027 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:50,334 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:50,645 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:50,852 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:50,955 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,266 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,575 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,853 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:51,886 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:52,196 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:52,507 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:52,815 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:52,853 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:53,132 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:53,806 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,853 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:54,853 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:55,807 ERROR   gpu       :514501 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:04:55,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,807 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,854 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:56,853 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,808 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,854 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:58,998 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,989 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:00,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:01,561 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,809 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,864 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:01,989 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:02,168 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:02,492 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:02,800 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:02,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:03,104 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,419 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,732 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,989 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:04,040 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:04,351 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:04,668 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:04,981 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:04,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:05,289 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,606 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,810 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,918 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:06,227 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:06,542 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:06,857 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:06,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:07,167 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:07,481 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:07,793 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,811 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:08,106 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:08,420 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:08,734 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:08,990 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:09,048 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,812 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:10,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:10,999 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,999 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:13,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:13,813 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:14,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:15,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:15,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,814 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:16,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:17,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:17,601 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,815 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,907 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:18,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:18,215 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:18,540 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:18,847 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,000 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:19,154 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,476 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,787 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:20,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:20,098 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:20,417 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:20,728 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:21,043 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,355 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,669 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,816 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,982 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:22,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:22,292 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:22,607 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:22,918 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:23,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:23,228 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:23,544 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,817 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,856 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:24,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:24,167 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:24,481 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:24,796 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:25,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:25,108 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,818 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:26,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:27,001 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:28,002 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:29,002 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:29,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,819 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:30,002 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:31,018 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,820 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:32,007 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:33,007 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:33,393 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:33,702 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:34,008 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:34,011 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:34,336 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:34,646 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:34,953 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,008 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:35,271 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,586 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,821 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,894 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:36,009 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:36,210 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:36,527 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:36,836 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,008 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:37,150 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,469 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,781 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,822 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:38,008 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:38,094 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:38,409 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:38,725 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:39,008 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:39,037 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:39,351 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:39,666 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,823 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,977 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:40,009 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:40,293 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:40,610 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:40,923 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:41,009 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:42,009 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:43,009 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:43,824 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:44,012 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:45,012 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:45,521 ERROR   SenderThread:514501 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:05:45,521 ERROR   SenderThread:514501 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5EkVG was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:05:45,825 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,826 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,826 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,826 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,826 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,826 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,826 ERROR   gpu       :514501 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:45,924 INFO    WriterThread:514501 [datastore.py:close():296] close: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5EkVG/run-Miner-5EkVG.wandb
2024-09-10 17:05:46,012 DEBUG   HandlerThread:514501 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:46,012 INFO    HandlerThread:514501 [handler.py:finish():880] shutting down handler
2024-09-10 17:05:46,012 INFO    HandlerThread:514501 [system_monitor.py:finish():203] Stopping system monitor
2024-09-10 17:05:46,012 DEBUG   SystemMonitor:514501 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-10 17:05:46,014 ERROR   gpu       :514501 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:05:46,014 INFO    HandlerThread:514501 [interfaces.py:finish():200] Joined cpu monitor
2024-09-10 17:05:46,014 DEBUG   SystemMonitor:514501 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-10 17:05:46,014 INFO    HandlerThread:514501 [interfaces.py:finish():200] Joined disk monitor
2024-09-10 17:05:46,016 INFO    HandlerThread:514501 [interfaces.py:finish():200] Joined gpu monitor
2024-09-10 17:05:46,016 INFO    HandlerThread:514501 [interfaces.py:finish():200] Joined memory monitor
2024-09-10 17:05:46,017 INFO    HandlerThread:514501 [interfaces.py:finish():200] Joined network monitor
2024-09-10 17:05:46,291 ERROR   StreamThr :514501 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2224, in upsert_run
    response = self.gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 92, in _run
    self._debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 333, in _debounce
    self._sm.debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 549, in debounce
    self._maybe_update_config(always=final)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 526, in _maybe_update_config
    self._debounce_config()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 555, in _debounce_config
    self._api.upsert_run(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run Miner-5EkVG was previously created and deleted; try a new run name (Error 409: Conflict)
