2024-09-10 17:08:41,962 INFO    StreamThr :532386 [internal.py:wandb_internal():85] W&B internal server running at pid: 532386, started at: 2024-09-10 17:08:41.962132
2024-09-10 17:08:41,964 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:08:41,965 INFO    WriterThread:532386 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/run-xiu516w1.wandb
2024-09-10 17:08:41,967 DEBUG   SenderThread:532386 [sender.py:send():391] send: header
2024-09-10 17:08:41,968 DEBUG   SenderThread:532386 [sender.py:send():391] send: run
2024-09-10 17:08:42,180 INFO    SenderThread:532386 [dir_watcher.py:__init__():211] watching files in: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/files
2024-09-10 17:08:42,180 INFO    SenderThread:532386 [sender.py:_start_run_threads():1200] run started: xiu516w1 with start time 1725988121.96156
2024-09-10 17:08:42,190 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: check_version
2024-09-10 17:08:42,190 DEBUG   SenderThread:532386 [sender.py:send_request():418] send_request: check_version
2024-09-10 17:08:42,249 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: run_start
2024-09-10 17:08:43,964 DEBUG   HandlerThread:532386 [system_info.py:__init__():26] System info init
2024-09-10 17:08:43,965 DEBUG   HandlerThread:532386 [system_info.py:__init__():41] System info init done
2024-09-10 17:08:43,965 INFO    HandlerThread:532386 [system_monitor.py:start():194] Starting system monitor
2024-09-10 17:08:43,965 INFO    SystemMonitor:532386 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-10 17:08:43,965 INFO    HandlerThread:532386 [system_monitor.py:probe():214] Collecting system info
2024-09-10 17:08:43,966 INFO    SystemMonitor:532386 [interfaces.py:start():188] Started cpu monitoring
2024-09-10 17:08:43,966 INFO    SystemMonitor:532386 [interfaces.py:start():188] Started disk monitoring
2024-09-10 17:08:43,967 INFO    SystemMonitor:532386 [interfaces.py:start():188] Started gpu monitoring
2024-09-10 17:08:43,968 INFO    SystemMonitor:532386 [interfaces.py:start():188] Started memory monitoring
2024-09-10 17:08:43,969 INFO    SystemMonitor:532386 [interfaces.py:start():188] Started network monitoring
2024-09-10 17:08:44,636 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,637 DEBUG   HandlerThread:532386 [system_info.py:probe():152] Probing system
2024-09-10 17:08:44,639 DEBUG   HandlerThread:532386 [system_info.py:_probe_git():137] Probing git
2024-09-10 17:08:44,645 DEBUG   HandlerThread:532386 [system_info.py:_probe_git():145] Probing git done
2024-09-10 17:08:44,645 DEBUG   HandlerThread:532386 [system_info.py:probe():200] Probing system done
2024-09-10 17:08:44,645 DEBUG   HandlerThread:532386 [system_monitor.py:probe():223] {'os': 'Linux-5.19.0-1010-nvidia-lowlatency-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-09-10T17:08:44.637349', 'startedAt': '2024-09-10T17:08:41.957677', 'docker': None, 'cuda': None, 'args': ('--wallet.name', 'Alice', '--wallet.hotkey', 'Dave', '--subtensor.network', 'test', '--device', 'cuda:4', '--use_wandb'), 'state': 'running', 'program': '/home/ubuntu/frontend/bistro/miner.py', 'codePathLocal': 'miner.py', 'codePath': 'bistro/miner.py', 'git': {'remote': 'https://github.com/unconst/frontend.git', 'commit': 'a0660981f23476af1751d70673e4586879b6970c'}, 'email': 'jake@bittensor.com', 'root': '/home/ubuntu/frontend', 'host': 'training', 'username': 'ubuntu', 'executable': '/home/ubuntu/frontend/venv/bin/python3', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2253.343265625, 'min': 1500.0, 'max': 3250.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1637.054, 'min': 1500.0, 'max': 3250.0}, {'current': 2169.957, 'min': 1500.0, 'max': 3250.0}, {'current': 3799.6, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.433, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.112, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3789.916, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.094, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.139, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3796.562, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1519.572, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1310.315, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.11, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.141, 'min': 1500.0, 'max': 3250.0}, {'current': 2171.412, 'min': 1500.0, 'max': 3250.0}, {'current': 1787.464, 'min': 1500.0, 'max': 3250.0}, {'current': 2171.513, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3797.592, 'min': 1500.0, 'max': 3250.0}, {'current': 3787.085, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3794.213, 'min': 1500.0, 'max': 3250.0}, {'current': 3250.0, 'min': 1500.0, 'max': 3250.0}, {'current': 3800.137, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3250.0}], 'disk': {'/': {'total': 3519.6199798583984, 'used': 90.96330642700195}}, 'gpu': 'NVIDIA H100 PCIe', 'gpu_count': 8, 'memory': {'total': 1511.5785369873047}}
2024-09-10 17:08:44,645 INFO    HandlerThread:532386 [system_monitor.py:probe():224] Finished collecting system info
2024-09-10 17:08:44,645 INFO    HandlerThread:532386 [system_monitor.py:probe():227] Publishing system info
2024-09-10 17:08:44,647 INFO    HandlerThread:532386 [system_monitor.py:probe():229] Finished publishing system info
2024-09-10 17:08:44,649 DEBUG   SenderThread:532386 [sender.py:send():391] send: files
2024-09-10 17:08:44,650 INFO    SenderThread:532386 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-09-10 17:08:44,694 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,736 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,736 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,736 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,736 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,744 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:44,790 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: python_packages
2024-09-10 17:08:44,791 DEBUG   SenderThread:532386 [sender.py:send_request():418] send_request: python_packages
2024-09-10 17:08:44,791 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:08:44,792 DEBUG   SenderThread:532386 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:08:44,793 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:44,928 DEBUG   SenderThread:532386 [sender.py:send():391] send: telemetry
2024-09-10 17:08:45,183 INFO    Thread-12 :532386 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/files/wandb-metadata.json
2024-09-10 17:08:45,183 INFO    Thread-12 :532386 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/files/requirements.txt
2024-09-10 17:08:45,601 INFO    wandb-upload_0:532386 [upload_job.py:push():130] Uploaded file /tmp/tmp7s8gv6v0wandb/yhop45yx-wandb-metadata.json
2024-09-10 17:08:45,882 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:46,744 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,745 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,745 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,745 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,745 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,745 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,745 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:46,867 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:47,158 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:08:47,160 DEBUG   SenderThread:532386 [sender.py:send():391] send: history
2024-09-10 17:08:47,161 DEBUG   SenderThread:532386 [sender.py:send_request():418] send_request: summary_record
2024-09-10 17:08:47,162 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:08:47,162 INFO    SenderThread:532386 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-10 17:08:47,182 INFO    Thread-12 :532386 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/files/wandb-summary.json
2024-09-10 17:08:47,867 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:48,182 INFO    Thread-12 :532386 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/files/output.log
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:48,868 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:49,233 ERROR   FileStreamThread:532386 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/const69/bistro/xiu516w1/file_stream
NoneType: None
2024-09-10 17:08:49,867 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:50,183 INFO    Thread-12 :532386 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/files/output.log
2024-09-10 17:08:50,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,867 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:50,871 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,871 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:50,872 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:51,867 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:52,792 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:08:52,868 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:08:52,908 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,320 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,320 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,320 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:54,321 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,400 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,429 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,429 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,430 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,430 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,430 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:56,430 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:57,793 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:08:59,301 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,305 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,306 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,306 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,306 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,306 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:08:59,306 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,307 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:01,324 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:02,794 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:09:04,419 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:04,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,555 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,587 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,588 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,588 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,588 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,588 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:06,588 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:07,796 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:09:08,644 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,679 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,679 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,679 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,679 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,679 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:08,679 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,771 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,808 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,808 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,808 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,809 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,809 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:10,809 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:11,944 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:09:11,945 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:11,945 DEBUG   SenderThread:532386 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:09:12,942 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:13,005 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,070 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:09:13,103 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,104 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,104 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,104 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:13,104 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:13,105 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,105 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,105 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:13,943 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:14,333 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:14,333 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:14,942 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:15,162 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,226 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,226 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,226 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,226 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,226 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,226 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:15,942 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:16,563 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:16,563 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:16,563 INFO    SenderThread:532386 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:09:16,944 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:17,312 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,410 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,411 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,411 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,411 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,411 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,411 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:17,943 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:18,943 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:19,411 ERROR   gpu       :532386 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:09:19,481 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,537 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,537 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,537 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,537 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,537 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,537 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:19,943 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:20,944 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:21,208 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:21,208 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:21,575 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,661 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,661 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,661 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,661 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,661 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:21,661 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:22,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:23,371 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:23,730 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,866 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,867 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,867 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,867 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,867 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:23,867 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:24,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:25,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:25,937 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,006 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,006 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,006 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,006 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,006 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,006 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:26,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:26,944 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:09:27,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:28,114 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,245 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,246 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,246 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,246 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,246 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,246 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:28,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:29,372 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:30,360 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,438 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,438 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,438 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,438 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,438 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,438 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:30,602 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:31,184 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:31,185 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:31,602 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:32,501 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,602 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:32,643 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,643 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,643 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,643 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,643 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:32,643 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:33,602 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:34,602 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:34,710 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:34,747 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:35,603 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:36,602 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:36,840 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,943 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,944 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,944 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,944 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,944 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:36,944 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:37,603 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:38,603 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:38,996 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,063 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,063 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,064 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,064 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,064 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,064 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:39,603 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:40,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:41,101 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,195 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,195 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,195 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,195 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,195 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,195 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:41,603 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:42,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:43,234 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,267 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,267 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,267 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,267 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,267 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,267 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:43,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:43,969 DEBUG   SystemMonitor:532386 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-10 17:09:44,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:45,298 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,337 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,338 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,338 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,338 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,338 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,338 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:45,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:46,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:47,453 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,562 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,563 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,563 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,563 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,563 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,563 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:47,604 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:48,605 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:49,605 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:49,610 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,635 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,636 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,636 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,636 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,636 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:49,636 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:50,605 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:50,799 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:09:50,799 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:09:51,605 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:51,636 ERROR   gpu       :532386 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:09:51,696 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,786 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,786 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,786 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,786 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,786 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:51,786 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:52,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:53,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:53,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,860 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,861 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,861 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,861 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,861 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:53,861 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:54,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:55,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:55,864 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,023 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,023 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,023 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,024 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,024 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,024 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:56,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:57,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:58,083 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,149 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,150 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,150 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,150 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,150 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,150 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:09:58,606 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:09:59,607 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:00,213 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,309 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,309 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,309 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,309 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,309 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,309 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:00,607 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:01,607 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:02,389 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,475 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,475 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,475 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,475 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,475 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,475 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:02,872 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:03,872 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:04,627 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,741 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,741 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,741 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,741 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,741 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,741 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:04,872 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:05,873 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:06,766 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,838 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,838 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,838 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,839 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,839 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,839 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:06,872 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:07,873 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:08,873 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:08,876 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,905 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,905 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,905 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,905 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,905 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:08,905 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:09,873 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:10,873 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:10,950 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,000 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,000 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,000 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,000 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,000 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,000 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:11,873 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:12,874 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:13,014 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,100 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,100 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,101 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,101 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,101 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,101 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:13,874 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:14,874 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:15,112 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,198 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,198 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,198 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,198 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,198 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,198 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:15,874 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:16,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:17,229 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,279 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,279 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,279 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,279 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,279 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,279 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:17,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:18,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:19,256 WARNING FileStreamThread:532386 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: 502 Server Error: Bad Gateway for url: https://api.wandb.ai/files/const69/bistro/xiu516w1/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f9c7555baf0>>, args: ('https://api.wandb.ai/files/const69/bistro/xiu516w1/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 1, 'uploaded': []}}
2024-09-10 17:10:19,288 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,335 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,335 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,335 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,335 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,335 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,335 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:19,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:20,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:21,360 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,425 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,425 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,425 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,425 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,425 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,425 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:21,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:22,875 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:23,031 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:10:23,031 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:10:23,425 ERROR   gpu       :532386 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:10:23,448 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,476 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,476 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,476 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,477 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,477 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,477 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:23,876 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:24,876 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:25,522 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,566 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,566 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,566 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,566 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,566 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,566 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:25,877 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:26,876 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:27,589 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,591 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,591 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,591 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,591 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,591 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,592 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:27,877 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:28,877 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:29,610 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,649 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,649 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,649 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,649 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,649 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,649 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:29,877 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:30,878 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:31,686 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,748 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,748 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,748 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,748 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:31,878 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:32,878 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:33,749 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:34,063 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:35,029 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:35,798 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,814 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,814 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,814 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:35,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:36,028 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:37,029 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:37,442 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:37,815 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:38,029 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:39,029 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:39,608 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:39,931 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:40,029 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:40,220 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:40,509 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:40,798 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,029 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:41,087 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,376 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,665 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:41,816 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:41,954 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:42,030 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:42,243 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:42,532 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:42,821 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,030 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:43,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,398 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,687 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,817 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:43,976 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,030 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:44,264 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,553 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:44,842 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,030 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:45,131 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,420 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,709 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,818 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:45,998 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:46,030 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:46,286 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:46,576 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:47,031 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:47,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:48,031 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:49,031 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:49,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,819 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:49,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:50,032 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:51,032 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:51,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,820 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:51,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:52,032 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:53,032 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:53,821 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:54,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:54,781 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:55,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:55,070 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:55,359 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:55,648 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:55,937 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:56,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:56,226 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:56,515 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:56,804 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:57,093 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,382 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,671 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:57,822 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:57,960 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:58,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:58,249 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:58,538 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:58,827 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:10:59,116 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,405 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,693 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:10:59,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,823 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:10:59,983 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,033 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:00,271 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,560 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:00,849 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,034 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:01,138 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,427 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,715 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:01,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:02,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:03,039 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:03,824 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:03,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:04,039 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:05,039 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:05,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,825 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:05,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:06,039 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:07,039 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:07,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,826 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:07,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:08,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:09,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,827 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:09,911 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:10,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:10,199 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:10,489 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:10,778 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:11,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:11,067 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:11,356 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:11,645 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,828 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:11,934 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:12,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:12,223 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:12,513 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:12,802 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,040 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:13,091 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,380 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,669 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:13,960 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:14,041 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:14,248 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:14,537 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:14,826 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,041 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:15,115 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,404 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,693 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:15,829 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:15,982 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:16,041 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:16,271 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:16,559 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:16,848 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:11:17,114 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:17,830 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:18,098 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:19,098 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:19,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:20,098 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:21,098 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:21,831 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,832 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,832 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,832 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,832 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,832 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:21,832 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:22,125 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:23,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:23,832 ERROR   gpu       :532386 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:23,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:24,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:25,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:25,833 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:25,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:26,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:27,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:27,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,834 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:27,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:28,109 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:29,126 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:29,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,835 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:29,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:30,110 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:31,110 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:31,755 ERROR   SenderThread:532386 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:11:31,756 ERROR   SenderThread:532386 [internal_api.py:execute():350] {"errors":[{"message":"run xiu516w1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:31,836 ERROR   gpu       :532386 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:11:32,110 DEBUG   HandlerThread:532386 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:11:32,110 INFO    HandlerThread:532386 [handler.py:finish():880] shutting down handler
2024-09-10 17:11:32,110 INFO    HandlerThread:532386 [system_monitor.py:finish():203] Stopping system monitor
2024-09-10 17:11:32,110 ERROR   gpu       :532386 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:11:32,111 DEBUG   SystemMonitor:532386 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-10 17:11:32,112 INFO    HandlerThread:532386 [interfaces.py:finish():200] Joined cpu monitor
2024-09-10 17:11:32,112 DEBUG   SystemMonitor:532386 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-10 17:11:32,112 INFO    HandlerThread:532386 [interfaces.py:finish():200] Joined disk monitor
2024-09-10 17:11:32,115 INFO    HandlerThread:532386 [interfaces.py:finish():200] Joined gpu monitor
2024-09-10 17:11:32,115 INFO    HandlerThread:532386 [interfaces.py:finish():200] Joined memory monitor
2024-09-10 17:11:32,115 INFO    HandlerThread:532386 [interfaces.py:finish():200] Joined network monitor
2024-09-10 17:11:32,175 INFO    WriterThread:532386 [datastore.py:close():296] close: /home/ubuntu/frontend/bistro/wandb/run-20240910_170841-xiu516w1/run-xiu516w1.wandb
2024-09-10 17:11:32,176 ERROR   StreamThr :532386 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2224, in upsert_run
    response = self.gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 92, in _run
    self._debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 333, in _debounce
    self._sm.debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 549, in debounce
    self._maybe_update_config(always=final)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 526, in _maybe_update_config
    self._debounce_config()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 555, in _debounce_config
    self._api.upsert_run(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run xiu516w1 was previously created and deleted; try a new run name (Error 409: Conflict)
