2024-09-10 17:02:47,119 INFO    StreamThr :514510 [internal.py:wandb_internal():85] W&B internal server running at pid: 514510, started at: 2024-09-10 17:02:47.119068
2024-09-10 17:02:47,121 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:02:47,123 INFO    WriterThread:514510 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/run-Miner-5GQw7.wandb
2024-09-10 17:02:47,123 DEBUG   SenderThread:514510 [sender.py:send():391] send: header
2024-09-10 17:02:47,125 DEBUG   SenderThread:514510 [sender.py:send():391] send: run
2024-09-10 17:02:47,129 INFO    SenderThread:514510 [sender.py:_setup_resume():761] checking resume status for None/bistro/Miner-5GQw7
2024-09-10 17:02:47,290 INFO    SenderThread:514510 [sender.py:_setup_resume():841] configured resuming with: ResumeState(resumed=True,step=1,history=1,events=0,output=6,runtime=5,wandb_runtime=None,summary={'_runtime': 5.23658561706543, '_step': 0, '_timestamp': 1725987641.7503786, 'block': 2767843, 'master': 0, 'step': 1},config={'history_size': {'value': 4}, 'optimizer_weight_decay': {'value': 0.1}, 'bucket': {'value': 'decis'}, '_wandb': {'value': {'python_version': '3.10.12', 'is_kaggle_kernel': False, 'huggingface_version': '4.44.2', 't': {'4': '3.10.12', '5': '0.17.7', '6': '4.44.2', '8': [5], '13': 'linux-x86_64', '1': [1, 11, 49, 55, 71], '2': [1, 11, 49, 55, 71], '3': [13, 14, 16, 23]}, 'framework': 'huggingface', 'start_time': 1725987636, 'cli_version': '0.17.7', 'is_jupyter_run': False}}, 'netuid': {'value': 212}, 'device': {'value': 'cuda:4'}, 'config': {'value': None}, 'optimizer_beta1': {'value': 0.9}, 'subtensor': {'value': {'_mock': False, 'network': 'test', 'chain_endpoint': 'wss://entrypoint-finney.opentensor.ai:443'}}, 'batch_size': {'value': 4}, 'optimizer_beta2': {'value': 0.95}, 'use_wandb': {'value': True}, 'eval_window': {'value': 5}, 'wallet': {'value': {'hotkey': 'Dave', 'path': '~/.bittensor/wallets/', 'name': 'Alice'}}, 'strict': {'value': False}, 'learning_rate': {'value': 0.0001}, 'name': {'value': None}, '__is_set': {'value': {'use_wandb': True, 'wallet.hotkey': True, 'subtensor.network': True, 'device': True, 'wallet.name': True}}, 'no_prompt': {'value': False}, 'no_version_checking': {'value': False}},tags=[])
2024-09-10 17:02:47,424 INFO    SenderThread:514510 [dir_watcher.py:__init__():211] watching files in: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files
2024-09-10 17:02:47,424 INFO    SenderThread:514510 [sender.py:_start_run_threads():1200] run started: Miner-5GQw7 with start time 1725987762.118848
2024-09-10 17:02:47,427 DEBUG   SenderThread:514510 [sender.py:send_request():418] send_request: summary_record
2024-09-10 17:02:47,427 INFO    SenderThread:514510 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-10 17:02:47,436 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: check_version
2024-09-10 17:02:47,436 DEBUG   SenderThread:514510 [sender.py:send_request():418] send_request: check_version
2024-09-10 17:02:47,500 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: run_start
2024-09-10 17:02:48,425 INFO    Thread-12 :514510 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files/wandb-summary.json
2024-09-10 17:02:49,477 DEBUG   HandlerThread:514510 [system_info.py:__init__():26] System info init
2024-09-10 17:02:49,477 DEBUG   HandlerThread:514510 [system_info.py:__init__():41] System info init done
2024-09-10 17:02:49,477 INFO    HandlerThread:514510 [system_monitor.py:start():194] Starting system monitor
2024-09-10 17:02:49,477 INFO    SystemMonitor:514510 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-10 17:02:49,478 INFO    SystemMonitor:514510 [interfaces.py:start():188] Started cpu monitoring
2024-09-10 17:02:49,480 INFO    SystemMonitor:514510 [interfaces.py:start():188] Started disk monitoring
2024-09-10 17:02:49,481 INFO    SystemMonitor:514510 [interfaces.py:start():188] Started gpu monitoring
2024-09-10 17:02:49,482 INFO    SystemMonitor:514510 [interfaces.py:start():188] Started memory monitoring
2024-09-10 17:02:49,482 INFO    SystemMonitor:514510 [interfaces.py:start():188] Started network monitoring
2024-09-10 17:02:49,616 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: python_packages
2024-09-10 17:02:49,616 DEBUG   SenderThread:514510 [sender.py:send_request():418] send_request: python_packages
2024-09-10 17:02:49,616 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:02:49,618 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:49,618 DEBUG   SenderThread:514510 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:02:49,707 DEBUG   SenderThread:514510 [sender.py:send():391] send: telemetry
2024-09-10 17:02:50,035 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,064 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,209 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,209 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,209 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,209 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,212 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:50,425 INFO    Thread-12 :514510 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files/requirements.txt
2024-09-10 17:02:50,668 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:51,622 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:51,768 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:02:51,770 DEBUG   SenderThread:514510 [sender.py:send():391] send: history
2024-09-10 17:02:51,770 DEBUG   SenderThread:514510 [sender.py:send_request():418] send_request: summary_record
2024-09-10 17:02:51,772 INFO    SenderThread:514510 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-10 17:02:52,212 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,212 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:52,425 INFO    Thread-12 :514510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files/wandb-summary.json
2024-09-10 17:02:52,426 INFO    Thread-12 :514510 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files/output.log
2024-09-10 17:02:52,622 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:52,811 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:02:53,622 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:54,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,213 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,214 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:54,426 INFO    Thread-12 :514510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files/output.log
2024-09-10 17:02:54,622 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:55,622 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:56,293 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:56,622 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:02:58,349 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,377 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,378 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:02:58,617 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:00,404 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:00,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,416 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,421 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:02,422 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:03,618 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:04,471 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,473 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:04,474 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,571 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,641 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,641 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,641 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,641 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,641 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:06,641 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,229 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:03:08,230 DEBUG   SenderThread:514510 [sender.py:send_request():418] send_request: stop_status
2024-09-10 17:03:08,270 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:08,702 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,730 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,730 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,730 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,730 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,730 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:08,731 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:09,229 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:09,291 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:10,229 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:10,772 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:10,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:11,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:11,708 ERROR   FileStreamThread:514510 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/const69/bistro/Miner-5GQw7/file_stream
NoneType: None
2024-09-10 17:03:12,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:12,432 INFO    Thread-12 :514510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/files/output.log
2024-09-10 17:03:13,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:13,234 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,237 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,237 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,238 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,238 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,238 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:13,238 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:14,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:15,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:15,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:15,272 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:15,341 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:16,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,387 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:17,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:18,387 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:19,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:19,412 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,540 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,540 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,540 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,540 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,540 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:19,540 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:20,232 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: status_report
2024-09-10 17:03:20,266 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:20,266 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:20,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:21,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:21,476 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:21,476 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:21,540 ERROR   gpu       :514510 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:03:21,577 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,605 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:21,606 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:22,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:23,229 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: stop_status
2024-09-10 17:03:23,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:23,657 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,695 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,696 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,696 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,696 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,696 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:23,868 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:23,869 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:23,869 INFO    SenderThread:514510 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:03:24,388 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:25,389 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:25,753 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:25,757 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:26,389 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:27,389 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:27,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,007 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:28,389 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:29,378 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:29,378 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:29,389 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:30,100 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,130 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:30,390 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:32,016 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:32,169 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,238 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,238 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:32,239 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:33,016 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:34,017 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:34,277 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:34,367 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:35,017 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:36,017 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:36,444 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,545 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:36,546 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:37,017 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:37,918 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:37,918 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:38,017 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:38,634 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,666 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:38,667 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:39,017 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:40,038 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:40,689 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:40,690 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:41,038 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:42,038 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:42,723 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:42,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:43,038 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:44,038 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:44,883 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,885 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,886 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:44,886 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:45,038 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:46,039 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:46,966 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,039 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:47,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:47,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:48,039 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:49,133 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,135 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,135 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,135 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,135 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,135 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,135 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:49,438 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:49,482 DEBUG   SystemMonitor:514510 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-10 17:03:50,437 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:51,161 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,201 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,202 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,202 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,202 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,202 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,202 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:51,437 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:52,438 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:53,202 ERROR   gpu       :514510 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:03:53,257 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,295 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:53,438 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:54,439 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:55,261 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:03:55,261 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:03:55,371 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,406 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:55,438 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:56,439 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:57,439 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:57,454 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,457 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,457 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,457 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,457 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,457 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:57,457 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:58,439 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:59,439 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:03:59,472 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,553 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,553 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,553 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,553 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,553 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:03:59,553 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:00,439 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:01,440 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:01,636 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,693 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,693 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,693 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,693 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,693 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:01,693 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:02,440 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:03,479 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:03,771 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:03,904 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:03,905 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:03,905 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:03,905 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:03,905 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:03,905 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:04,477 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:05,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:06,034 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,127 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,127 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,127 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,127 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,127 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,127 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:06,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:07,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:08,170 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,211 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,211 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,211 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,211 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,211 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,211 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:08,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:09,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:10,245 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,339 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,340 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,340 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,340 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,340 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,340 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:10,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:11,478 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:12,395 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,479 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:12,485 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,485 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,485 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,485 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,485 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:12,485 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:13,479 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:14,479 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:14,567 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:14,649 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:15,479 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:16,480 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:16,705 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,759 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,759 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,759 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,759 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,759 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:16,759 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:17,480 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:18,480 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:18,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:18,866 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:19,480 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:20,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:20,903 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,952 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:20,953 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:21,480 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:22,480 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:23,028 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,090 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:23,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:24,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:25,090 ERROR   gpu       :514510 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:04:25,169 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,173 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:25,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:26,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:27,212 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,282 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:27,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:28,481 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,321 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:29,482 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:30,482 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:31,411 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,513 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:31,514 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,482 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:04:33,482 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:04:33,580 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,672 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,673 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,673 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,673 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:33,673 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,751 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:35,784 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,792 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,799 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,800 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,800 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,800 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:37,800 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:38,458 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:04:38,580 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:04:38,580 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:39,494 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:39,801 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:39,802 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:40,494 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:41,494 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:41,803 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:42,042 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:42,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:43,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:43,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:44,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:44,995 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:45,312 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:45,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:45,614 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:45,804 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:45,924 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:46,231 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:46,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:46,533 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:46,839 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,148 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,450 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:47,755 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:47,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,805 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:47,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:48,062 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,367 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,496 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:48,671 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:48,981 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:49,287 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:49,496 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:49,590 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:49,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,806 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:49,896 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:50,206 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:50,496 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:50,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:50,816 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,126 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,432 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,496 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:51,739 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:51,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,807 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:51,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:52,048 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:52,353 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:04:52,497 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:53,496 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:53,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,808 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:53,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:54,497 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:55,497 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:55,809 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:56,497 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:57,497 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:57,810 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,810 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,810 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,810 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,810 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,810 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:57,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:58,499 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:59,499 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:04:59,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,811 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:04:59,812 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:00,428 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:00,499 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:00,730 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:01,034 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:01,353 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:01,499 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:01,655 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:01,812 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,812 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,812 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,813 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,813 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,813 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,813 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:01,957 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:02,271 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:02,500 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:02,581 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:02,884 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,193 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,500 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:03,503 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,810 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:03,813 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,813 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:03,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:04,118 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:04,432 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:04,500 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:04,739 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,047 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,356 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,500 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:05,667 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:05,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,814 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:05,973 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:06,282 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:06,500 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:06,594 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:06,901 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:07,210 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:07,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:07,520 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,815 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:07,831 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:08,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:09,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:09,816 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:10,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:11,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:11,817 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:12,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:13,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:13,818 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,818 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,819 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,819 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,819 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,819 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:13,819 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:14,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:15,501 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:15,819 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:15,928 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:16,230 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:16,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:16,536 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:16,856 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:17,161 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:17,466 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:17,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:17,780 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:17,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,820 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:17,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:18,091 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:18,397 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:18,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:18,710 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,023 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,331 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:19,642 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,821 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:19,954 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:20,261 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:20,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:20,570 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:20,879 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,190 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,495 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:21,805 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:21,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,822 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:21,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:22,115 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:22,421 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:22,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:22,730 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:23,040 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:23,349 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:23,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:23,823 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:24,502 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:25,503 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:25,824 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:26,503 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:27,503 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:27,825 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,825 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,825 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,825 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,826 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,826 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:27,826 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:28,526 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:29,508 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:29,826 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,826 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,826 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:29,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:30,150 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:30,452 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:30,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:30,763 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:31,084 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:31,392 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:31,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:31,694 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:31,827 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:32,011 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:32,325 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:32,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:32,630 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:32,944 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:33,254 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:33,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:33,559 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,828 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:33,870 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:34,182 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:34,490 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:34,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:34,796 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,108 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,417 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:35,727 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:35,829 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:36,036 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:36,348 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:36,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:36,657 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:36,965 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,277 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,509 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:37,588 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: partial_history
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:37,830 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:38,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:39,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:39,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:40,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:41,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:41,831 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:41,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:42,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:43,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:43,672 ERROR   SenderThread:514510 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:05:43,672 ERROR   SenderThread:514510 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:05:43,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,832 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,833 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,833 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:43,833 ERROR   gpu       :514510 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-10 17:05:44,363 INFO    WriterThread:514510 [datastore.py:close():296] close: /home/ubuntu/frontend/bistro/wandb/run-20240910_170247-Miner-5GQw7/run-Miner-5GQw7.wandb
2024-09-10 17:05:44,510 DEBUG   HandlerThread:514510 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-10 17:05:44,511 INFO    HandlerThread:514510 [handler.py:finish():880] shutting down handler
2024-09-10 17:05:44,511 INFO    HandlerThread:514510 [system_monitor.py:finish():203] Stopping system monitor
2024-09-10 17:05:44,511 DEBUG   SystemMonitor:514510 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-10 17:05:44,512 INFO    HandlerThread:514510 [interfaces.py:finish():200] Joined cpu monitor
2024-09-10 17:05:44,512 DEBUG   SystemMonitor:514510 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-10 17:05:44,512 ERROR   gpu       :514510 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-09-10 17:05:44,513 INFO    HandlerThread:514510 [interfaces.py:finish():200] Joined disk monitor
2024-09-10 17:05:44,515 INFO    HandlerThread:514510 [interfaces.py:finish():200] Joined gpu monitor
2024-09-10 17:05:44,515 INFO    HandlerThread:514510 [interfaces.py:finish():200] Joined memory monitor
2024-09-10 17:05:44,515 INFO    HandlerThread:514510 [interfaces.py:finish():200] Joined network monitor
2024-09-10 17:05:44,515 ERROR   StreamThr :514510 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2224, in upsert_run
    response = self.gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 92, in _run
    self._debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 333, in _debounce
    self._sm.debounce()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 549, in debounce
    self._maybe_update_config(always=final)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 526, in _maybe_update_config
    self._debounce_config()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 555, in _debounce_config
    self._api.upsert_run(
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run Miner-5GQw7 was previously created and deleted; try a new run name (Error 409: Conflict)
